name: tails_mobile
description: Production-ready template for Flutter applications.
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

workspace:
  - packages/rest_client
  - packages/app_database

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.0
  async: ^2.11.0
  meta: ^1.15.0
  intl: ^0.20.2

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.28.0

  # BLoC
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  bloc_concurrency: ^0.3.0

  # Networking
  http: ^1.2.2
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.1
  intercepted_client: ^0.0.1

  # Storing data
  shared_preferences: ^2.3.2
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  flutter_secure_storage: ^10.0.0

  # Routing
  go_router: ^17.0.1

  # Logging
  stack_trace: ^1.11.1
  sentry_flutter: ^8.9.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3

  # Packages
  rest_client:
    path: packages/rest_client
  app_database:
    path: packages/app_database

  # Utils
  path: ^1.9.0
  path_provider: ^2.1.5
  clock: ^1.1.1
  fake_async: ^1.3.1
  package_info_plus: ^8.1.0
  flutter_gen: ^5.12.0
  theme_tailor: ^3.1.2
  flutter_svg: ^2.0.17
  equatable: ^2.0.8
  mask_text_input_formatter: ^2.9.0
  smooth_page_indicator: ^2.0.1
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_picker_plus: ^1.5.4

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

  # Lints
  sizzle_lints: ^2.1.3

  # Utils
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  build_runner: ^2.10.4
  go_router_builder: ^4.1.3
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/src/core/ui_kit/generated
  line_length: 100
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: UiAssets

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
